"""empty message

Revision ID: d7dc7d0fcfb6
Revises: 5f020c7b13c4
Create Date: 2024-12-04 22:38:42.754039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dc7d0fcfb6'
down_revision = '5f020c7b13c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_disabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_disabled')

    # ### end Alembic commands ###
